[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "insta-reader"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "instagrapi",
    "python-dotenv",
]

[project.scripts]
instagram-login = "scripts.instagram_login:main"

